# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateTemplateRequest(TypedDict):
    # The friendly display name for the template.
    Name: str

    # The Subject template definition for this Template.
    Subject: str

class OptionalCreateTemplateRequest(TypedDict, total=False):
    # The optional string identifier for referring to this Template (numbers, letters, and '.', '-', '_' characters, starts with a letter).
    Alias: str

    # The HTML template definition for this Template.
    HtmlBody: str

    # The Text template definition for this Template.
    TextBody: str

class CreateTemplateRequest(RequiredCreateTemplateRequest, OptionalCreateTemplateRequest):
    pass
