# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from postmark_python_sdk.type.bounce_count_element import BounceCountElement

class RequiredDeliveryStatsResponse(TypedDict):
    pass

class OptionalDeliveryStatsResponse(TypedDict, total=False):
    Bounces: typing.List[BounceCountElement]

    InactiveMails: int

class DeliveryStatsResponse(RequiredDeliveryStatsResponse, OptionalDeliveryStatsResponse):
    pass
