# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEditServerConfigurationRequest(TypedDict):
    pass

class OptionalEditServerConfigurationRequest(TypedDict, total=False):
    BounceHookUrl: str

    # Webhook url allowing real-time notification when tracked links are clicked.
    ClickHookUrl: str

    Color: str

    DeliveryHookUrl: str

    InboundDomain: str

    InboundHookUrl: str

    InboundSpamThreshold: int

    Name: str

    OpenHookUrl: str

    PostFirstOpenOnly: bool

    RawEmailEnabled: bool

    SmtpApiActivated: bool

    TrackLinks: str

    TrackOpens: bool

class EditServerConfigurationRequest(RequiredEditServerConfigurationRequest, OptionalEditServerConfigurationRequest):
    pass
