# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from postmark_python_sdk.type.attachment_collection import AttachmentCollection
from postmark_python_sdk.type.header_collection import HeaderCollection

class RequiredEmailWithTemplateRequest(TypedDict):
    From: str

    # Required if 'TemplateId' is not specified.
    TemplateAlias: str

    # Required if 'TemplateAlias' is not specified.
    TemplateId: int

    TemplateModel: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    To: str

class OptionalEmailWithTemplateRequest(TypedDict, total=False):
    Attachments: AttachmentCollection

    Bcc: str

    Cc: str

    Headers: HeaderCollection

    InlineCss: bool

    ReplyTo: str

    Tag: str

    # Replace links in content to enable \"click tracking\" stats. Default is 'null', which uses the server's LinkTracking setting'.
    TrackLinks: str

    # Activate open tracking for this email.
    TrackOpens: bool

class EmailWithTemplateRequest(RequiredEmailWithTemplateRequest, OptionalEmailWithTemplateRequest):
    pass
