# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredExtendedMessageOpenEventInformation(TypedDict):
    pass

class OptionalExtendedMessageOpenEventInformation(TypedDict, total=False):
    Client: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    FirstOpen: bool

    Geo: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    MessageID: str

    OS: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    Platform: str

    ReceivedAt: datetime

    Recipient: str

    Tag: str

    UserAgent: str

class ExtendedMessageOpenEventInformation(RequiredExtendedMessageOpenEventInformation, OptionalExtendedMessageOpenEventInformation):
    pass
