# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from postmark_python_sdk.type.attachment_collection import AttachmentCollection
from postmark_python_sdk.type.email_name_address_pair import EmailNameAddressPair
from postmark_python_sdk.type.header_collection import HeaderCollection

class RequiredInboundMessageFullDetailsResponse(TypedDict):
    pass

class OptionalInboundMessageFullDetailsResponse(TypedDict, total=False):
    Attachments: AttachmentCollection

    BlockedReason: str

    Cc: str

    CcFull: typing.List[EmailNameAddressPair]

    Date: str

    From: str

    FromFull: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    FromName: str

    Headers: HeaderCollection

    HtmlBody: str

    MailboxHash: str

    MessageID: str

    OriginalRecipient: str

    ReplyTo: str

    Status: str

    Subject: str

    Tag: str

    TextBody: str

    To: str

    ToFull: typing.List[EmailNameAddressPair]

class InboundMessageFullDetailsResponse(RequiredInboundMessageFullDetailsResponse, OptionalInboundMessageFullDetailsResponse):
    pass
