# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from postmark_python_sdk.type.extended_message_click_event_information import ExtendedMessageClickEventInformation

class RequiredMessageClickSearchResponse(TypedDict):
    pass

class OptionalMessageClickSearchResponse(TypedDict, total=False):
    Clicks: typing.List[ExtendedMessageClickEventInformation]

    TotalCount: int

class MessageClickSearchResponse(RequiredMessageClickSearchResponse, OptionalMessageClickSearchResponse):
    pass
