# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredMessageHeader(TypedDict):
    pass

class OptionalMessageHeader(TypedDict, total=False):
    # The header's name.
    Name: str

    # The header's value.
    Value: str

class MessageHeader(RequiredMessageHeader, OptionalMessageHeader):
    pass
