# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from postmark_python_sdk.type.attachment_collection import AttachmentCollection
from postmark_python_sdk.type.email_name_address_pair import EmailNameAddressPair

class RequiredOutboundMessageDetail(TypedDict):
    pass

class OptionalOutboundMessageDetail(TypedDict, total=False):
    Attachments: AttachmentCollection

    Bcc: typing.List[EmailNameAddressPair]

    Cc: typing.List[EmailNameAddressPair]

    From: str

    MessageID: str

    ReceivedAt: datetime

    Recipients: typing.List[str]

    Status: str

    Subject: str

    Tag: str

    To: typing.List[EmailNameAddressPair]

    TrackLinks: str

    TrackOpens: bool

class OutboundMessageDetail(RequiredOutboundMessageDetail, OptionalOutboundMessageDetail):
    pass
