# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from postmark_python_sdk.type.attachment_collection import AttachmentCollection
from postmark_python_sdk.type.header_collection import HeaderCollection

class RequiredSendEmailRequest(TypedDict):
    pass

class OptionalSendEmailRequest(TypedDict, total=False):
    Attachments: AttachmentCollection

    # Bcc recipient email address. Multiple addresses are comma seperated. Max 50.
    Bcc: str

    # Recipient email address. Multiple addresses are comma seperated. Max 50.
    Cc: str

    # The sender email address. Must have a registered and confirmed Sender Signature.
    From: str

    Headers: HeaderCollection

    # If no TextBody specified HTML email message
    HtmlBody: str

    # Reply To override email address. Defaults to the Reply To set in the sender signature.
    ReplyTo: str

    # Email Subject
    Subject: str

    # Email tag that allows you to categorize outgoing emails and get detailed statistics.
    Tag: str

    # If no HtmlBody specified Plain text email message
    TextBody: str

    # Recipient email address. Multiple addresses are comma seperated. Max 50.
    To: str

    # Replace links in content to enable \"click tracking\" stats. Default is 'null', which uses the server's LinkTracking setting'.
    TrackLinks: str

    # Activate open tracking for this email.
    TrackOpens: bool

class SendEmailRequest(RequiredSendEmailRequest, OptionalSendEmailRequest):
    pass
