# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredServerConfigurationResponse(TypedDict):
    pass

class OptionalServerConfigurationResponse(TypedDict, total=False):
    ApiTokens: typing.List[str]

    BounceHookUrl: str

    ClickHookUrl: str

    Color: str

    DeliveryHookUrl: str

    ID: int

    InboundAddress: str

    InboundDomain: str

    InboundHash: str

    InboundHookUrl: str

    InboundSpamThreshold: int

    Name: str

    OpenHookUrl: str

    PostFirstOpenOnly: bool

    RawEmailEnabled: bool

    ServerLink: str

    SmtpApiActivated: bool

    TrackLinks: str

    TrackOpens: bool

class ServerConfigurationResponse(RequiredServerConfigurationResponse, OptionalServerConfigurationResponse):
    pass
