# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTemplateDetailResponse(TypedDict):
    pass

class OptionalTemplateDetailResponse(TypedDict, total=False):
    # Indicates that this template may be used for sending email.
    Active: bool

    # The user-supplied alias for this template.
    Alias: str

    # The ID of the Server with which this template is associated.
    AssociatedServerId: int

    # The content to use for the HtmlBody when this template is used to send email.
    HtmlBody: str

    # The display name for the template.
    Name: str

    # The content to use for the Subject when this template is used to send email.
    Subject: str

    # The ID associated with the template.
    TemplateID: int

    # The content to use for the TextBody when this template is used to send email.
    TextBody: str

class TemplateDetailResponse(RequiredTemplateDetailResponse, OptionalTemplateDetailResponse):
    pass
