# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from postmark_python_sdk.type.template_validation_result import TemplateValidationResult

class RequiredTemplateValidationResponse(TypedDict):
    pass

class OptionalTemplateValidationResponse(TypedDict, total=False):
    AllContentIsValid: bool

    HtmlBody: TemplateValidationResult

    Subject: TemplateValidationResult

    SuggestedTemplateModel: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    TextBody: TemplateValidationResult

class TemplateValidationResponse(RequiredTemplateValidationResponse, OptionalTemplateValidationResponse):
    pass
