# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from postmark_python_sdk.type.template_record_response import TemplateRecordResponse

class RequiredTemplateListingResponse(TypedDict):
    pass

class OptionalTemplateListingResponse(TypedDict, total=False):
    # Basic information for each Template returned from the query.
    Templates API: typing.List[TemplateRecordResponse]

    # The total number of Templates API associated with this server.
    TotalCount: typing.Union[int, float]

class TemplateListingResponse(RequiredTemplateListingResponse, OptionalTemplateListingResponse):
    pass
