# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from postmark_python_sdk import Postmark

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        postmark = Postmark(
        
                        server_token = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(postmark)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
