# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import postmark_python_sdk
from postmark_python_sdk.paths.stats_outbound_bounces import get
from postmark_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestStatsOutboundBounces(ApiTestMixin, unittest.TestCase):
    """
    StatsOutboundBounces unit test stubs
        Get bounce counts
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
