# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import postmark_python_sdk
from postmark_python_sdk.model.bounce_info_response import BounceInfoResponse
from postmark_python_sdk import configuration


class TestBounceInfoResponse(unittest.TestCase):
    """BounceInfoResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
