# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import postmark_python_sdk
from postmark_python_sdk.model.attachment import Attachment
from postmark_python_sdk import configuration


class TestAttachment(unittest.TestCase):
    """Attachment unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
