# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from postmark_python_sdk.pydantic.bounce_info_response import BounceInfoResponse

class BounceActivationResponse(BaseModel):
    bounce: typing.Optional[BounceInfoResponse] = Field(None, alias='Bounce')

    message: typing.Optional[str] = Field(None, alias='Message')
    class Config:
        arbitrary_types_allowed = True
