# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class BounceInfoResponse(BaseModel):
    bounced_at: typing.Optional[datetime] = Field(None, alias='BouncedAt')

    can_activate: typing.Optional[bool] = Field(None, alias='CanActivate')

    content: typing.Optional[str] = Field(None, alias='Content')

    description: typing.Optional[str] = Field(None, alias='Description')

    details: typing.Optional[str] = Field(None, alias='Details')

    dump_available: typing.Optional[bool] = Field(None, alias='DumpAvailable')

    email: typing.Optional[str] = Field(None, alias='Email')

    i_d: typing.Optional[str] = Field(None, alias='ID')

    inactive: typing.Optional[bool] = Field(None, alias='Inactive')

    message_i_d: typing.Optional[str] = Field(None, alias='MessageID')

    name: typing.Optional[str] = Field(None, alias='Name')

    subject: typing.Optional[str] = Field(None, alias='Subject')

    tag: typing.Optional[str] = Field(None, alias='Tag')

    type: typing.Optional[str] = Field(None, alias='Type')

    type_code: typing.Optional[int] = Field(None, alias='TypeCode')
    class Config:
        arbitrary_types_allowed = True
