# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CreateTemplateRequest(BaseModel):
    # The friendly display name for the template.
    name: str = Field(alias='Name')

    # The Subject template definition for this Template.
    subject: str = Field(alias='Subject')

    # The optional string identifier for referring to this Template (numbers, letters, and '.', '-', '_' characters, starts with a letter).
    alias: typing.Optional[str] = Field(None, alias='Alias')

    # The HTML template definition for this Template.
    html_body: typing.Optional[str] = Field(None, alias='HtmlBody')

    # The Text template definition for this Template.
    text_body: typing.Optional[str] = Field(None, alias='TextBody')
    class Config:
        arbitrary_types_allowed = True
