# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from postmark_python_sdk.pydantic.bounce_count_element import BounceCountElement

class DeliveryStatsResponse(BaseModel):
    bounces: typing.Optional[typing.List[BounceCountElement]] = Field(None, alias='Bounces')

    inactive_mails: typing.Optional[int] = Field(None, alias='InactiveMails')
    class Config:
        arbitrary_types_allowed = True
