# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class EmailNameAddressPair(BaseModel):
    email: typing.Optional[str] = Field(None, alias='Email')

    name: typing.Optional[str] = Field(None, alias='Name')
    class Config:
        arbitrary_types_allowed = True
