# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class MessageEventDetails(BaseModel):
    details: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='Details')

    received_at: typing.Optional[datetime] = Field(None, alias='ReceivedAt')

    recipient: typing.Optional[str] = Field(None, alias='Recipient')

    type: typing.Optional[str] = Field(None, alias='Type')
    class Config:
        arbitrary_types_allowed = True
