# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from postmark_python_sdk.pydantic.email_with_template_request import EmailWithTemplateRequest

class SendEmailTemplatedBatchRequest(BaseModel):
    messages: typing.Optional[typing.List[EmailWithTemplateRequest]] = Field(None, alias='Messages')
    class Config:
        arbitrary_types_allowed = True
