# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ServerConfigurationResponse(BaseModel):
    api_tokens: typing.Optional[typing.List[str]] = Field(None, alias='ApiTokens')

    bounce_hook_url: typing.Optional[str] = Field(None, alias='BounceHookUrl')

    click_hook_url: typing.Optional[str] = Field(None, alias='ClickHookUrl')

    color: typing.Optional[Literal["purple", "blue", "turqoise", "green", "red", "yellow", "grey"]] = Field(None, alias='Color')

    delivery_hook_url: typing.Optional[str] = Field(None, alias='DeliveryHookUrl')

    i_d: typing.Optional[int] = Field(None, alias='ID')

    inbound_address: typing.Optional[str] = Field(None, alias='InboundAddress')

    inbound_domain: typing.Optional[str] = Field(None, alias='InboundDomain')

    inbound_hash: typing.Optional[str] = Field(None, alias='InboundHash')

    inbound_hook_url: typing.Optional[str] = Field(None, alias='InboundHookUrl')

    inbound_spam_threshold: typing.Optional[int] = Field(None, alias='InboundSpamThreshold')

    name: typing.Optional[str] = Field(None, alias='Name')

    open_hook_url: typing.Optional[str] = Field(None, alias='OpenHookUrl')

    post_first_open_only: typing.Optional[bool] = Field(None, alias='PostFirstOpenOnly')

    raw_email_enabled: typing.Optional[bool] = Field(None, alias='RawEmailEnabled')

    server_link: typing.Optional[str] = Field(None, alias='ServerLink')

    smtp_api_activated: typing.Optional[bool] = Field(None, alias='SmtpApiActivated')

    track_links: typing.Optional[Literal["None", "HtmlAndText", "HtmlOnly", "TextOnly"]] = Field(None, alias='TrackLinks')

    track_opens: typing.Optional[bool] = Field(None, alias='TrackOpens')
    class Config:
        arbitrary_types_allowed = True
