# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from postmark_python_sdk.pydantic.template_record_response import TemplateRecordResponse

class TemplateListingResponse(BaseModel):
    # Basic information for each Template returned from the query.
    templates _a_p_i_: typing.Optional[typing.List[TemplateRecordResponse]] = Field(None, alias='Templates API')

    # The total number of Templates API associated with this server.
    total_count: typing.Optional[typing.Union[int, float]] = Field(None, alias='TotalCount')
    class Config:
        arbitrary_types_allowed = True
