# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TemplateRecordResponse(BaseModel):
    # True if this template is currently available for use.
    active: typing.Optional[bool] = Field(None, alias='Active')

    # The user-supplied alias for this template.
    alias: typing.Optional[str] = Field(None, alias='Alias')

    # The display name for this template.
    name: typing.Optional[str] = Field(None, alias='Name')

    # The associated ID for this template.
    template_id: typing.Optional[typing.Union[int, float]] = Field(None, alias='TemplateId')
    class Config:
        arbitrary_types_allowed = True
