# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TemplateDetailResponse(BaseModel):
    # Indicates that this template may be used for sending email.
    active: typing.Optional[bool] = Field(None, alias='Active')

    # The user-supplied alias for this template.
    alias: typing.Optional[str] = Field(None, alias='Alias')

    # The ID of the Server with which this template is associated.
    associated_server_id: typing.Optional[int] = Field(None, alias='AssociatedServerId')

    # The content to use for the HtmlBody when this template is used to send email.
    html_body: typing.Optional[str] = Field(None, alias='HtmlBody')

    # The display name for the template.
    name: typing.Optional[str] = Field(None, alias='Name')

    # The content to use for the Subject when this template is used to send email.
    subject: typing.Optional[str] = Field(None, alias='Subject')

    # The ID associated with the template.
    template_i_d: typing.Optional[int] = Field(None, alias='TemplateID')

    # The content to use for the TextBody when this template is used to send email.
    text_body: typing.Optional[str] = Field(None, alias='TextBody')
    class Config:
        arbitrary_types_allowed = True
