# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from postmark_python_sdk import schemas  # noqa: F401


class DeliveryStatsResponse(
    schemas.AnyTypeSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class Bounces(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['BounceCountElement']:
                        return BounceCountElement
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['BounceCountElement'], typing.List['BounceCountElement']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Bounces':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'BounceCountElement':
                    return super().__getitem__(i)
            InactiveMails = schemas.IntSchema
            __annotations__ = {
                "Bounces": Bounces,
                "InactiveMails": InactiveMails,
            }

    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Bounces"]) -> MetaOapg.properties.Bounces: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["InactiveMails"]) -> MetaOapg.properties.InactiveMails: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Bounces", "InactiveMails", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Bounces"]) -> typing.Union[MetaOapg.properties.Bounces, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["InactiveMails"]) -> typing.Union[MetaOapg.properties.InactiveMails, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Bounces", "InactiveMails", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        Bounces: typing.Union[MetaOapg.properties.Bounces, list, tuple, schemas.Unset] = schemas.unset,
        InactiveMails: typing.Union[MetaOapg.properties.InactiveMails, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DeliveryStatsResponse':
        return super().__new__(
            cls,
            *args,
            Bounces=Bounces,
            InactiveMails=InactiveMails,
            _configuration=_configuration,
            **kwargs,
        )

from postmark_python_sdk.model.bounce_count_element import BounceCountElement
