# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from postmark_python_sdk import schemas  # noqa: F401


class HeaderCollection(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['MessageHeader']:
            return MessageHeader

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['MessageHeader'], typing.List['MessageHeader']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'HeaderCollection':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'MessageHeader':
        return super().__getitem__(i)

from postmark_python_sdk.model.message_header import MessageHeader
