# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.bounces_bounceid_activate.put import ActivateBounceRaw
from postmark_python_sdk.paths.bounces_bounceid.get import GetBounceRaw
from postmark_python_sdk.paths.deliverystats.get import GetDeliveryStatsRaw
from postmark_python_sdk.paths.bounces_bounceid_dump.get import GetDumpRaw
from postmark_python_sdk.paths.bounces.get import ListBouncesRaw


class BouncesAPIApiRaw(
    ActivateBounceRaw,
    GetBounceRaw,
    GetDeliveryStatsRaw,
    GetDumpRaw,
    ListBouncesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
