# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.bounces_bounceid_activate.put import ActivateBounce
from postmark_python_sdk.paths.bounces_bounceid.get import GetBounce
from postmark_python_sdk.paths.deliverystats.get import GetDeliveryStats
from postmark_python_sdk.paths.bounces_bounceid_dump.get import GetDump
from postmark_python_sdk.paths.bounces.get import ListBounces
from postmark_python_sdk.apis.tags.bounces_api_api_raw import BouncesAPIApiRaw


class BouncesAPIApi(
    ActivateBounce,
    GetBounce,
    GetDeliveryStats,
    GetDump,
    ListBounces,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BouncesAPIApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BouncesAPIApiRaw(api_client)
