# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.triggers_inboundrules.post import CreateTriggerRaw
from postmark_python_sdk.paths.triggers_inboundrules_triggerid.delete import DeleteSingleTriggerRaw
from postmark_python_sdk.paths.triggers_inboundrules.get import ListTriggersRaw


class InboundRulesAPIApiRaw(
    CreateTriggerRaw,
    DeleteSingleTriggerRaw,
    ListTriggersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
