# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.messages_outbound_clicks.get import GetAllClicks
from postmark_python_sdk.paths.messages_inbound_messageid_details.get import GetInboundMessageDetails
from postmark_python_sdk.paths.messages_outbound_clicks_messageid.get import GetMessageClicks
from postmark_python_sdk.paths.messages_outbound_messageid_dump.get import GetMessageDump
from postmark_python_sdk.paths.messages_outbound_opens_messageid.get import GetMessageOpens
from postmark_python_sdk.paths.messages_outbound_messageid_details.get import GetOutboundMessageDetails
from postmark_python_sdk.paths.messages_outbound_opens.get import ListOpensForOutbound
from postmark_python_sdk.paths.messages_inbound_messageid_retry.put import RetryInboundMessage
from postmark_python_sdk.paths.messages_inbound.get import SearchInboundMessages
from postmark_python_sdk.paths.messages_outbound.get import SearchOutboundMessages
from postmark_python_sdk.paths.messages_inbound_messageid_bypass.put import UpdateBypassRulesForInboundMessage
from postmark_python_sdk.apis.tags.messages_api_api_raw import MessagesAPIApiRaw


class MessagesAPIApi(
    GetAllClicks,
    GetInboundMessageDetails,
    GetMessageClicks,
    GetMessageDump,
    GetMessageOpens,
    GetOutboundMessageDetails,
    ListOpensForOutbound,
    RetryInboundMessage,
    SearchInboundMessages,
    SearchOutboundMessages,
    UpdateBypassRulesForInboundMessage,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MessagesAPIApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MessagesAPIApiRaw(api_client)
