# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.messages_outbound_clicks.get import GetAllClicksRaw
from postmark_python_sdk.paths.messages_inbound_messageid_details.get import GetInboundMessageDetailsRaw
from postmark_python_sdk.paths.messages_outbound_clicks_messageid.get import GetMessageClicksRaw
from postmark_python_sdk.paths.messages_outbound_messageid_dump.get import GetMessageDumpRaw
from postmark_python_sdk.paths.messages_outbound_opens_messageid.get import GetMessageOpensRaw
from postmark_python_sdk.paths.messages_outbound_messageid_details.get import GetOutboundMessageDetailsRaw
from postmark_python_sdk.paths.messages_outbound_opens.get import ListOpensForOutboundRaw
from postmark_python_sdk.paths.messages_inbound_messageid_retry.put import RetryInboundMessageRaw
from postmark_python_sdk.paths.messages_inbound.get import SearchInboundMessagesRaw
from postmark_python_sdk.paths.messages_outbound.get import SearchOutboundMessagesRaw
from postmark_python_sdk.paths.messages_inbound_messageid_bypass.put import UpdateBypassRulesForInboundMessageRaw


class MessagesAPIApiRaw(
    GetAllClicksRaw,
    GetInboundMessageDetailsRaw,
    GetMessageClicksRaw,
    GetMessageDumpRaw,
    GetMessageOpensRaw,
    GetOutboundMessageDetailsRaw,
    ListOpensForOutboundRaw,
    RetryInboundMessageRaw,
    SearchInboundMessagesRaw,
    SearchOutboundMessagesRaw,
    UpdateBypassRulesForInboundMessageRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
