# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.email_batch.post import SendBatchEmails
from postmark_python_sdk.paths.email_batch_with_templates.post import SendBatchWithTemplates
from postmark_python_sdk.paths.email_with_template.post import SendEmailTemplate
from postmark_python_sdk.paths.email.post import SendSingleEmail
from postmark_python_sdk.apis.tags.sending_api_api_raw import SendingAPIApiRaw


class SendingAPIApi(
    SendBatchEmails,
    SendBatchWithTemplates,
    SendEmailTemplate,
    SendSingleEmail,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SendingAPIApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SendingAPIApiRaw(api_client)
