# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.server.get import GetConfigurationRaw
from postmark_python_sdk.paths.server.put import UpdateConfigurationRaw


class ServerConfigurationAPIApiRaw(
    GetConfigurationRaw,
    UpdateConfigurationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
