# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.stats_outbound_bounces.get import GetBounceCountsRaw
from postmark_python_sdk.paths.stats_outbound_clicks_platforms.get import GetBrowserPlatformUsageRaw
from postmark_python_sdk.paths.stats_outbound_opens_emailclients.get import GetEmailClientUsageRaw
from postmark_python_sdk.paths.stats_outbound_opens.get import GetEmailOpenCountsRaw
from postmark_python_sdk.paths.stats_outbound_opens_platforms.get import GetEmailPlatformUsageRaw
from postmark_python_sdk.paths.stats_outbound_clicks.get import GetOutboundClickCountsRaw
from postmark_python_sdk.paths.stats_outbound_clicks_browserfamilies.get import GetOutboundClicksBrowserFamiliesRaw
from postmark_python_sdk.paths.stats_outbound_clicks_location.get import GetOutboundClicksLocationRaw
from postmark_python_sdk.paths.stats_outbound.get import GetOutboundOverviewRaw
from postmark_python_sdk.paths.stats_outbound_sends.get import GetSentCountsRaw
from postmark_python_sdk.paths.stats_outbound_spam.get import GetSpamComplaintsRaw
from postmark_python_sdk.paths.stats_outbound_tracked.get import GetTrackedEmailCountsRaw


class StatsAPIApiRaw(
    GetBounceCountsRaw,
    GetBrowserPlatformUsageRaw,
    GetEmailClientUsageRaw,
    GetEmailOpenCountsRaw,
    GetEmailPlatformUsageRaw,
    GetOutboundClickCountsRaw,
    GetOutboundClicksBrowserFamiliesRaw,
    GetOutboundClicksLocationRaw,
    GetOutboundOverviewRaw,
    GetSentCountsRaw,
    GetSpamComplaintsRaw,
    GetTrackedEmailCountsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
