# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from postmark_python_sdk.paths.templates.post import CreateTemplateRaw
from postmark_python_sdk.paths.templates_template_id_or_alias.delete import DeleteTemplateRaw
from postmark_python_sdk.paths.templates_template_id_or_alias.get import GetTemplateByIdRaw
from postmark_python_sdk.paths.templates.get import ListTemplatesRaw
from postmark_python_sdk.paths.email_batch_with_templates.post import SendBatchWithTemplatesRaw
from postmark_python_sdk.paths.email_with_template.post import SendEmailTemplateRaw
from postmark_python_sdk.paths.templates_template_id_or_alias.put import UpdateTemplateRaw
from postmark_python_sdk.paths.templates_validate.post import ValidateTemplateContentRaw


class TemplatesAPIApiRaw(
    CreateTemplateRaw,
    DeleteTemplateRaw,
    GetTemplateByIdRaw,
    ListTemplatesRaw,
    SendBatchWithTemplatesRaw,
    SendEmailTemplateRaw,
    UpdateTemplateRaw,
    ValidateTemplateContentRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
