# coding: utf-8

# flake8: noqa

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from postmark_python_sdk.api_client import ApiClient

# import Configuration
from postmark_python_sdk.configuration import Configuration

# import exceptions
from postmark_python_sdk.exceptions import OpenApiException
from postmark_python_sdk.exceptions import ApiAttributeError
from postmark_python_sdk.exceptions import ApiTypeError
from postmark_python_sdk.exceptions import ApiValueError
from postmark_python_sdk.exceptions import ApiKeyError
from postmark_python_sdk.exceptions import ApiException

from postmark_python_sdk.client import Postmark
