# coding: utf-8
"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from postmark_python_sdk.client_custom import ClientCustom
from postmark_python_sdk.configuration import Configuration
from postmark_python_sdk.api_client import ApiClient
from postmark_python_sdk.type_util import copy_signature
from postmark_python_sdk.apis.tags.bounces_api_api import BouncesAPIApi
from postmark_python_sdk.apis.tags.inbound_rules_api_api import InboundRulesAPIApi
from postmark_python_sdk.apis.tags.messages_api_api import MessagesAPIApi
from postmark_python_sdk.apis.tags.sending_api_api import SendingAPIApi
from postmark_python_sdk.apis.tags.server_configuration_api_api import ServerConfigurationAPIApi
from postmark_python_sdk.apis.tags.stats_api_api import StatsAPIApi
from postmark_python_sdk.apis.tags.templates_api_api import TemplatesAPIApi



class Postmark(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.bounces_api: BouncesAPIApi = BouncesAPIApi(api_client)
        self.inbound_rules_api: InboundRulesAPIApi = InboundRulesAPIApi(api_client)
        self.messages_api: MessagesAPIApi = MessagesAPIApi(api_client)
        self.sending_api: SendingAPIApi = SendingAPIApi(api_client)
        self.server_configuration_api: ServerConfigurationAPIApi = ServerConfigurationAPIApi(api_client)
        self.stats_api: StatsAPIApi = StatsAPIApi(api_client)
        self.templates_api: TemplatesAPIApi = TemplatesAPIApi(api_client)
