# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from postmark_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from postmark_python_sdk.api_response import AsyncGeneratorResponse
from postmark_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from postmark_python_sdk import schemas  # noqa: F401

from postmark_python_sdk.model.bounce_search_response import BounceSearchResponse as BounceSearchResponseSchema
from postmark_python_sdk.model.standard_postmark_response import StandardPostmarkResponse as StandardPostmarkResponseSchema

from postmark_python_sdk.type.bounce_search_response import BounceSearchResponse
from postmark_python_sdk.type.standard_postmark_response import StandardPostmarkResponse

from ...api_client import Dictionary
from postmark_python_sdk.pydantic.standard_postmark_response import StandardPostmarkResponse as StandardPostmarkResponsePydantic
from postmark_python_sdk.pydantic.bounce_search_response import BounceSearchResponse as BounceSearchResponsePydantic

from . import path

# Query params


class CountSchema(
    schemas.IntSchema
):


    class MetaOapg:
        inclusive_maximum = 500
OffsetSchema = schemas.IntSchema


class TypeSchema(
    schemas.EnumBase,
    schemas.StrSchema
):


    class MetaOapg:
        enum_value_to_name = {
            "HardBounce": "HARD_BOUNCE",
            "Transient": "TRANSIENT",
            "Unsubscribe": "UNSUBSCRIBE",
            "Subscribe": "SUBSCRIBE",
            "AutoResponder": "AUTO_RESPONDER",
            "AddressChange": "ADDRESS_CHANGE",
            "DnsError": "DNS_ERROR",
            "SpamNotification": "SPAM_NOTIFICATION",
            "OpenRelayTest": "OPEN_RELAY_TEST",
            "Unknown": "UNKNOWN",
            "SoftBounce": "SOFT_BOUNCE",
            "VirusNotification": "VIRUS_NOTIFICATION",
            "MailFrontier Matador.": "MAIL_FRONTIER_MATADOR_",
            "BadEmailAddress": "BAD_EMAIL_ADDRESS",
            "SpamComplaint": "SPAM_COMPLAINT",
            "ManuallyDeactivated": "MANUALLY_DEACTIVATED",
            "Unconfirmed": "UNCONFIRMED",
            "Blocked": "BLOCKED",
            "SMTPApiError": "SMTPAPI_ERROR",
            "InboundError": "INBOUND_ERROR",
            "DMARCPolicy": "DMARCPOLICY",
            "TemplateRenderingFailed": "TEMPLATE_RENDERING_FAILED",
        }
    
    @schemas.classproperty
    def HARD_BOUNCE(cls):
        return cls("HardBounce")
    
    @schemas.classproperty
    def TRANSIENT(cls):
        return cls("Transient")
    
    @schemas.classproperty
    def UNSUBSCRIBE(cls):
        return cls("Unsubscribe")
    
    @schemas.classproperty
    def SUBSCRIBE(cls):
        return cls("Subscribe")
    
    @schemas.classproperty
    def AUTO_RESPONDER(cls):
        return cls("AutoResponder")
    
    @schemas.classproperty
    def ADDRESS_CHANGE(cls):
        return cls("AddressChange")
    
    @schemas.classproperty
    def DNS_ERROR(cls):
        return cls("DnsError")
    
    @schemas.classproperty
    def SPAM_NOTIFICATION(cls):
        return cls("SpamNotification")
    
    @schemas.classproperty
    def OPEN_RELAY_TEST(cls):
        return cls("OpenRelayTest")
    
    @schemas.classproperty
    def UNKNOWN(cls):
        return cls("Unknown")
    
    @schemas.classproperty
    def SOFT_BOUNCE(cls):
        return cls("SoftBounce")
    
    @schemas.classproperty
    def VIRUS_NOTIFICATION(cls):
        return cls("VirusNotification")
    
    @schemas.classproperty
    def MAIL_FRONTIER_MATADOR_(cls):
        return cls("MailFrontier Matador.")
    
    @schemas.classproperty
    def BAD_EMAIL_ADDRESS(cls):
        return cls("BadEmailAddress")
    
    @schemas.classproperty
    def SPAM_COMPLAINT(cls):
        return cls("SpamComplaint")
    
    @schemas.classproperty
    def MANUALLY_DEACTIVATED(cls):
        return cls("ManuallyDeactivated")
    
    @schemas.classproperty
    def UNCONFIRMED(cls):
        return cls("Unconfirmed")
    
    @schemas.classproperty
    def BLOCKED(cls):
        return cls("Blocked")
    
    @schemas.classproperty
    def SMTPAPI_ERROR(cls):
        return cls("SMTPApiError")
    
    @schemas.classproperty
    def INBOUND_ERROR(cls):
        return cls("InboundError")
    
    @schemas.classproperty
    def DMARCPOLICY(cls):
        return cls("DMARCPolicy")
    
    @schemas.classproperty
    def TEMPLATE_RENDERING_FAILED(cls):
        return cls("TemplateRenderingFailed")
InactiveSchema = schemas.BoolSchema
EmailFilterSchema = schemas.StrSchema
MessageIDSchema = schemas.StrSchema
TagSchema = schemas.StrSchema
TodateSchema = schemas.DateSchema
FromdateSchema = schemas.DateSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
        'count': typing.Union[CountSchema, decimal.Decimal, int, ],
        'offset': typing.Union[OffsetSchema, decimal.Decimal, int, ],
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'type': typing.Union[TypeSchema, str, ],
        'inactive': typing.Union[InactiveSchema, bool, ],
        'emailFilter': typing.Union[EmailFilterSchema, str, ],
        'messageID': typing.Union[MessageIDSchema, str, ],
        'tag': typing.Union[TagSchema, str, ],
        'todate': typing.Union[TodateSchema, str, date, ],
        'fromdate': typing.Union[FromdateSchema, str, date, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_count = api_client.QueryParameter(
    name="count",
    style=api_client.ParameterStyle.FORM,
    schema=CountSchema,
    required=True,
    explode=True,
)
request_query_offset = api_client.QueryParameter(
    name="offset",
    style=api_client.ParameterStyle.FORM,
    schema=OffsetSchema,
    required=True,
    explode=True,
)
request_query_type = api_client.QueryParameter(
    name="type",
    style=api_client.ParameterStyle.FORM,
    schema=TypeSchema,
    explode=True,
)
request_query_inactive = api_client.QueryParameter(
    name="inactive",
    style=api_client.ParameterStyle.FORM,
    schema=InactiveSchema,
    explode=True,
)
request_query_email_filter = api_client.QueryParameter(
    name="emailFilter",
    style=api_client.ParameterStyle.FORM,
    schema=EmailFilterSchema,
    explode=True,
)
request_query_message_id = api_client.QueryParameter(
    name="messageID",
    style=api_client.ParameterStyle.FORM,
    schema=MessageIDSchema,
    explode=True,
)
request_query_tag = api_client.QueryParameter(
    name="tag",
    style=api_client.ParameterStyle.FORM,
    schema=TagSchema,
    explode=True,
)
request_query_todate = api_client.QueryParameter(
    name="todate",
    style=api_client.ParameterStyle.FORM,
    schema=TodateSchema,
    explode=True,
)
request_query_fromdate = api_client.QueryParameter(
    name="fromdate",
    style=api_client.ParameterStyle.FORM,
    schema=FromdateSchema,
    explode=True,
)
_auth = [
    'serverToken',
]
SchemaFor200ResponseBodyApplicationJson = BounceSearchResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: BounceSearchResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: BounceSearchResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor422ResponseBodyApplicationJson = StandardPostmarkResponseSchema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: StandardPostmarkResponse


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: StandardPostmarkResponse


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
)
_status_code_to_response = {
    '200': _response_for_200,
    '422': _response_for_422,
    '500': _response_for_500,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _list_bounces_mapped_args(
        self,
        count: int,
        offset: int,
        type: typing.Optional[str] = None,
        inactive: typing.Optional[bool] = None,
        email_filter: typing.Optional[str] = None,
        message_id: typing.Optional[str] = None,
        tag: typing.Optional[str] = None,
        todate: typing.Optional[date] = None,
        fromdate: typing.Optional[date] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if count is not None:
            _query_params["count"] = count
        if offset is not None:
            _query_params["offset"] = offset
        if type is not None:
            _query_params["type"] = type
        if inactive is not None:
            _query_params["inactive"] = inactive
        if email_filter is not None:
            _query_params["emailFilter"] = email_filter
        if message_id is not None:
            _query_params["messageID"] = message_id
        if tag is not None:
            _query_params["tag"] = tag
        if todate is not None:
            _query_params["todate"] = todate
        if fromdate is not None:
            _query_params["fromdate"] = fromdate
        args.query = _query_params
        return args

    async def _alist_bounces_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get bounces
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_count,
            request_query_offset,
            request_query_type,
            request_query_inactive,
            request_query_email_filter,
            request_query_message_id,
            request_query_tag,
            request_query_todate,
            request_query_fromdate,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/bounces',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _list_bounces_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get bounces
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_count,
            request_query_offset,
            request_query_type,
            request_query_inactive,
            request_query_email_filter,
            request_query_message_id,
            request_query_tag,
            request_query_todate,
            request_query_fromdate,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/bounces',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ListBouncesRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def alist_bounces(
        self,
        count: int,
        offset: int,
        type: typing.Optional[str] = None,
        inactive: typing.Optional[bool] = None,
        email_filter: typing.Optional[str] = None,
        message_id: typing.Optional[str] = None,
        tag: typing.Optional[str] = None,
        todate: typing.Optional[date] = None,
        fromdate: typing.Optional[date] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_bounces_mapped_args(
            count=count,
            offset=offset,
            type=type,
            inactive=inactive,
            email_filter=email_filter,
            message_id=message_id,
            tag=tag,
            todate=todate,
            fromdate=fromdate,
        )
        return await self._alist_bounces_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def list_bounces(
        self,
        count: int,
        offset: int,
        type: typing.Optional[str] = None,
        inactive: typing.Optional[bool] = None,
        email_filter: typing.Optional[str] = None,
        message_id: typing.Optional[str] = None,
        tag: typing.Optional[str] = None,
        todate: typing.Optional[date] = None,
        fromdate: typing.Optional[date] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_bounces_mapped_args(
            count=count,
            offset=offset,
            type=type,
            inactive=inactive,
            email_filter=email_filter,
            message_id=message_id,
            tag=tag,
            todate=todate,
            fromdate=fromdate,
        )
        return self._list_bounces_oapg(
            query_params=args.query,
        )

class ListBounces(BaseApi):

    async def alist_bounces(
        self,
        count: int,
        offset: int,
        type: typing.Optional[str] = None,
        inactive: typing.Optional[bool] = None,
        email_filter: typing.Optional[str] = None,
        message_id: typing.Optional[str] = None,
        tag: typing.Optional[str] = None,
        todate: typing.Optional[date] = None,
        fromdate: typing.Optional[date] = None,
        validate: bool = False,
        **kwargs,
    ) -> BounceSearchResponsePydantic:
        raw_response = await self.raw.alist_bounces(
            count=count,
            offset=offset,
            type=type,
            inactive=inactive,
            email_filter=email_filter,
            message_id=message_id,
            tag=tag,
            todate=todate,
            fromdate=fromdate,
            **kwargs,
        )
        if validate:
            return BounceSearchResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(BounceSearchResponsePydantic, raw_response.body)
    
    
    def list_bounces(
        self,
        count: int,
        offset: int,
        type: typing.Optional[str] = None,
        inactive: typing.Optional[bool] = None,
        email_filter: typing.Optional[str] = None,
        message_id: typing.Optional[str] = None,
        tag: typing.Optional[str] = None,
        todate: typing.Optional[date] = None,
        fromdate: typing.Optional[date] = None,
        validate: bool = False,
    ) -> BounceSearchResponsePydantic:
        raw_response = self.raw.list_bounces(
            count=count,
            offset=offset,
            type=type,
            inactive=inactive,
            email_filter=email_filter,
            message_id=message_id,
            tag=tag,
            todate=todate,
            fromdate=fromdate,
        )
        if validate:
            return BounceSearchResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(BounceSearchResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        count: int,
        offset: int,
        type: typing.Optional[str] = None,
        inactive: typing.Optional[bool] = None,
        email_filter: typing.Optional[str] = None,
        message_id: typing.Optional[str] = None,
        tag: typing.Optional[str] = None,
        todate: typing.Optional[date] = None,
        fromdate: typing.Optional[date] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_bounces_mapped_args(
            count=count,
            offset=offset,
            type=type,
            inactive=inactive,
            email_filter=email_filter,
            message_id=message_id,
            tag=tag,
            todate=todate,
            fromdate=fromdate,
        )
        return await self._alist_bounces_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        count: int,
        offset: int,
        type: typing.Optional[str] = None,
        inactive: typing.Optional[bool] = None,
        email_filter: typing.Optional[str] = None,
        message_id: typing.Optional[str] = None,
        tag: typing.Optional[str] = None,
        todate: typing.Optional[date] = None,
        fromdate: typing.Optional[date] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_bounces_mapped_args(
            count=count,
            offset=offset,
            type=type,
            inactive=inactive,
            email_filter=email_filter,
            message_id=message_id,
            tag=tag,
            todate=todate,
            fromdate=fromdate,
        )
        return self._list_bounces_oapg(
            query_params=args.query,
        )

